name: Gametip

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,2,4,6,8,10,12,14,16,18,20,22 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      committed: ${{steps.commit.outputs.committed}}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: x64
      - name: Install dependencies
        run: pip install requests
      - name: Update Gametip
        env: 
          URL: ${{ secrets.URL }}
        run: |
          python gametip.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'Gametip auto update'
          add: '.'

  gitee-mirror:
    runs-on: ubuntu-latest
    needs: update
    if: needs.update.outputs.committed=='true'
    steps:
      - name: Mirror the Github repos to Gitee.
        # https://github.com/Yikun/hub-mirror-action
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/MengNianxiaoyao
          dst: gitee/MengNianxiaoyao
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: 'AzurLaneUncensored'
          account_type: user
          force_update: true
          timeout: '30m'
