name: Gitee mirror

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '*'
  schedule:
    # UTC 22:00 -> CST (China) 6:00
    - cron: '0 22 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github repos to Gitee.
        # https://github.com/Yikun/hub-mirror-action
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/MengNianxiaoyao
          dst: gitee/MengNianxiaoyao
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: 'AzurLaneUncensored'
          account_type: user
          force_update: true
          timeout: '30m'
