name: Update Assets

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,9 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      committed: ${{steps.commit.outputs.committed}}
    steps:
      - uses: actions/checkout@v4.1.2
      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.10'
          architecture: x64
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get install p7zip-full
      - name: Update Assets
        env: 
          URL: ${{ secrets.URL }}
        run: |
          python update.py
      - name: 提交更改
        id: 提交
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: github-actions
          author_email: github-actions[bot]@users.noreply.github.com
          message: 'assets auto update'
          add: '.'

  gitee-mirror:
    runs-on: ubuntu-latest
    needs: update
    if: needs.update.outputs.committed=='true'
    steps:
      - name: Mirror the Github repos to Gitee.
        # https://github.com/Yikun/hub-mirror-action
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/MengNianxiaoyao
          dst: gitee/MengNianxiaoyao
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: 'AzurLaneUncensored'
          account_type: user
          force_update: true
          timeout: '30m'
