name: Update Assets

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,2,4,6,8,10,12,14,16,18,20,22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: x64
      - name: Install dependencies
        run: pip install requests requests_cache
      - name: Update Assets
        env: 
          URL: ${{ secrets.URL }}
        run: |
          python update.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: 2589141604@qq.com
          message: 'assets auto update'
          add: '.'